apiVersion: v2
name: amityvox
description: A Helm chart for deploying AmityVox â€” a self-hosted, federated communication platform
type: application
version: 0.1.0
appVersion: "0.8.0"
home: https://github.com/amityvox/amityvox
sources:
  - https://github.com/amityvox/amityvox
maintainers:
  - name: AmityVox Team
keywords:
  - chat
  - communication
  - discord-alternative
  - self-hosted
  - federated
icon: https://amityvox.chat/icon.png
dependencies:
  - name: postgresql
    version: "~16.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: nats
    version: "~1.2"
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  - name: redis
    version: "~20.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    alias: dragonfly
  - name: meilisearch
    version: "~0.10"
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    condition: meilisearch.enabled
