apiVersion: v1
kind: Service
metadata:
  name: {{ include "amityvox.fullname" . }}
  labels:
    {{- include "amityvox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
    {{- if .Values.config.metrics.enabled }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "amityvox.selectorLabels" . | nindent 4 }}
